"""empty message

Revision ID: 44c48f7138f7
Revises: 71f71971b785
Create Date: 2023-08-05 01:18:58.467157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44c48f7138f7'
down_revision = '71f71971b785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_session', schema=None) as batch_op:
        batch_op.alter_column('validated',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('practitioner_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('data',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_session', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('practitioner_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('validated',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###
